### ISSUE TITLE
아스키코드표,한글 유니코드표

### ISSUE THREAD

**Issue by rlagustlr677** [rlagustlr677/steganography-dotnet#12]
http://luckey.tistory.com/227

**Comment by ur0n2** [comment]
ㅎㅇㅎㅅㄴㄷ

**Comment by ur0n2** [comment]
터키어 외에 한국어 지원도 하자는거군요!

**Comment by rlagustlr677** [comment]
예! 우리의 근본 한국어를 지원해보는건 어떨까해서요

**Comment by ur0n2** [comment]
근본은 101011101011...-.-..--.---...---... 아닙니까?

**Comment by SeungyeonKang** [comment]
네 아니구요 한국어 지원하는거 좋네요!

**Comment by ur0n2** [comment]
@SeungyeonKang 토론한거 내용정리해서 +터키아스키표랑 같이 올려주세여

**Comment by SeungyeonKang** [comment]
넵 터키어 아스키 코드표 자료입니다.

![1](https://cloud.githubusercontent.com/assets/23316009/20560194/5399d45c-b1bb-11e6-8bf3-1f6253d1937f.JPG)
![2](https://cloud.githubusercontent.com/assets/23316009/20560196/558885a6-b1bb-11e6-860b-c077b23ffb3a.JPG)

토론내용 👍 
 - 기존의 코드는 터키인이 제작한 코드임
 - 때문에, 기본 아스키 코드에 있는 영어 대/소문자와 숫자를 제외한 다른 입력 값은 터키어라고 판단해 if문으로 걸러냄
 - 한글도 아스키가 없으므로, 터키어처럼 if문을 이용하거나 한글을 지원하는 유니코드표를 사용해야 하는데, if문으로 모든 한글을 걸러내는 것은 불가능하고 유니코드표를 사용하면 8바이트로 표현이 어려우므로 프로그램의 전체적인 구조를 바꾸어야 함

 - **프로그램의 한글 지원 기능을 포기하는 것으로 결정**

**Comment by rlagustlr677** [comment]
기존에는 7비트의 문자열만이 입력이 가능하였다.(7비트 미만일 경우 0으로 패딩)
우리는 한글이 입력하고 싶어졌습니다.
한글은 16비트 문자열이기 때문에 7비트에 문자열에 넣을수 없고, 코드의 흐름을 크게 바꾸어야만 했습니다..
따라서 우리는 14비트 문자열로 입력받기로 하고, 한픽셀에 기존보다 2배가 넘는 메시지를 입력하였습니다.
우리는 한글을 14비트로 압축하여 삽입이 가능하고 기존 아스키에서 유니코드화로 바꾸었다.

![korean_understand](https://cloud.githubusercontent.com/assets/23314280/20717087/b76ec678-b697-11e6-913d-68ab21772471.JPG)

![korean_understand2](https://cloud.githubusercontent.com/assets/23314280/20717094/bcdf6c02-b697-11e6-8c55-3eb672dd5d20.JPG)

![korean_understand3](https://cloud.githubusercontent.com/assets/23314280/20717097/be9a2500-b697-11e6-9f55-56b57a5a7353.JPG)
