### ISSUE TITLE
GitHub의 이슈관리 기능 사용하기

### ISSUE THREAD

**Issue by SeungyeonKang** [rlagustlr677/steganography-dotnet#14]
https://www.lesstif.com/pages/viewpage.action?pageId=20775379 

깃헙 이슈관리기능 사용하는 방법입니다. 읽어봅시당

**Comment by SeungyeonKang** [comment]
네 감사해요~

**Comment by ur0n2** [comment]
스스로에게 감사하는 마음 본받겠습니다.
