### ISSUE TITLE
터키어 아스키표

### ISSUE THREAD

**Issue by SeungyeonKang** [rlagustlr677/steganography-dotnet#15]
![1](https://cloud.githubusercontent.com/assets/23316009/20559901/11794a7c-b1ba-11e6-8419-c8b8c81898ec.JPG)
![2](https://cloud.githubusercontent.com/assets/23316009/20559902/1215fb4c-b1ba-11e6-803e-a6125c8c43f4.JPG)

참고하세요

**Comment by ur0n2** [comment]
네 확인했습니다.
