### ISSUE TITLE
추가된 코드설명

### ISSUE THREAD

**Issue by rlagustlr677** [rlagustlr677/steganography-dotnet#18]
기존 R G B각 8비트중 마지막 1비트를 사용하는 방식에서, R G B 8비트중 마지막 2비트를 사용하는 방법으로 변경하였고 한글유니코드가 4만4천정도 부터 시작이기 때문에 이진수로 나타내면 16비트로 되어버려서 14비트안에다가 넣을 수가 없었습니다. 그래서 먼저 값을 읽어서 4만4천(Korea First index)보다 크면 4만3천을 빼서, 14비트 이내로 되게하고 14비트가 안될 시 0으로 패딩했습니다. 그리고 알파벳도 유니코드로 하고 나머지는 같슴..

**Comment by SeungyeonKang** [comment]
확인했습니다!

**Comment by ur0n2** [comment]
감사합니다.
