### ISSUE TITLE
라이센싱 합시다.

### ISSUE THREAD

**Issue by ur0n2** [rlagustlr677/steganography-dotnet#21]
아파치 기반 1일 1커밑 의무 라이센스 만들어서 달아버립시다.

이름 추천 고고!

**Comment by ur0n2** [comment]
ㅎㅇㅎㅅㄴㄷ 어때요?

**Comment by ur0n2** [comment]
ㄳㅎㅅㅇ도 좋고 ㅋㅋㅋ 맘대로 만들어봅시다.

**Comment by SeungyeonKang** [comment]
ㅎㅇㅎㅅㄴㄷ가 마음에 드네요!!!!

**Comment by ur0n2** [comment]
bpl 라이센스
beerware 라이센스
참조해서 다 작성했어여~! 내일안으로 커밑&클로즈 하겠습니다!

**Comment by ur0n2** [comment]
zzzz라이센스 작성했습니당. https://ur0n2.com/LICENSE.txt
