### ISSUE TITLE
물음표 이미지 바꾸기

### ISSUE THREAD

**Issue by ur0n2** [rlagustlr677/steganography-dotnet#22]
Questionmark Image Change

**Comment by ur0n2** [comment]
https://github.com/rlagustlr677/steganography-dotnet/blob/master/Resources/questionmark.jpg

이거 바꾸는거 제안한겁니까? @SeungyeonKang

**Comment by SeungyeonKang** [comment]
네 제안합니다. 이미지 괜찮은거 찾아보겠습니다!

**Comment by ur0n2** [comment]
브랜치 생성했습니다.
https://github.com/rlagustlr677/steganography-dotnet/tree/GUI_QUESTION_IMAGE_TEST/question_img_candidate

**Comment by SeungyeonKang** [comment]
넵 브랜치 폴더에 후보 이미지 업로드 하였습니다 골라주시기 바랍니다.

**Comment by ur0n2** [comment]
후보1에 한표요!

**Comment by rlagustlr677** [comment]
후보1이 좋군ㅇᆞ

**Comment by SeungyeonKang** [comment]
그럼 후보1로 결정겠습니다!
