### ISSUE TITLE
GUI 이쁘게 바꾸자는 의견 나왔었습니다.

### ISSUE THREAD

**Issue by SeungyeonKang** [rlagustlr677/steganography-dotnet#23]
GUI를 좀 꾸며볼까요~~~~

**Comment by SeungyeonKang** [comment]
먼저 아이콘을 바꿔보려고합니다. 넘나 칙칙한것

**Comment by ur0n2** [comment]
네네 좋아요.

**Comment by ur0n2** [comment]
![image](https://cloud.githubusercontent.com/assets/11265463/20674436/45df3766-b5cc-11e6-9765-ef2380ab4598.png)

와 이건가요?  ㅎㅎ 좋네요!

**Comment by SeungyeonKang** [comment]
GUI가 화사해졌습니다!
