### ISSUE TITLE
Wiki 아웃라인

### ISSUE THREAD

**Issue by ur0n2** [rlagustlr677/steganography-dotnet#25]
위키 아웃라인 잡읍시당 내일 낮 12시까지!

**Comment by ur0n2** [comment]
다 잡아갑니다! 콘텐츠 탐구도!

**Comment by ur0n2** [comment]
네 이제 위키 인라인 갑시다!

**Comment by ur0n2** [comment]
Wiki convention
- img는 검은색 테두리를 주고싶어요. border속성이 안먹히네요 ..
<img src="https://cloud.githubusercontent.com/assets/23293878/20676203/5544e380-b5d2-11e6-9487-73547fef72d5.png" border=5>

- 클립보드 사진 호스팅은 제 레포지터리 이슈를 이용해주세요.

- 내용 맨 앞에 스페이스바 한칸 회색 텍스트블록이 됩니다. 가로스크롤바 안생기도록 개행 해주시고요.

- 그리고 말머리번호도 붙여주세여. 초번은 붙여놓았습니다.

**Comment by SeungyeonKang** [comment]
넵 알겠습니다 감사합니다!

**Comment by rlagustlr677** [comment]
ㅎㅇㅎㅅㄴㄷ

**Comment by ur0n2** [comment]
위키 끝이요. 고생하셔습니다.
