### ISSUE TITLE
Readme.md 작성법

### ISSUE THREAD

**Issue by ur0n2** [rlagustlr677/steganography-dotnet#7]
https://gist.github.com/ihoneymon/652be052a0727ad59601

리드미를 마크다운으로 이쁘게 씁시당

**Comment by SeungyeonKang** [comment]
자료 잘 읽었습니다. 예쁘게 쓰면 좋을 것 같네요.

**Comment by SeungyeonKang** [comment]
자료 추가입니다. http://sergeswin.com/1013

**Comment by ur0n2** [comment]
참조요! 제껍니다!ㅋㅋ https://github.com/ur0n2/sqlzoo

**Comment by ur0n2** [comment]
오늘 12시내로 마무리하고 ㅠ 닫을게요.

**Comment by ur0n2** [comment]
완료했습니다!

**Comment by SeungyeonKang** [comment]
수고하셨습니다. 영어버전 추가하겠습니다!
