### ISSUE TITLE
steganography-dotnet/Importer.cs

### ISSUE THREAD

**Issue by ur0n2** [rlagustlr677/steganography-dotnet#8]
@rlagustlr677 코드리뷰해주세여

**Comment by rlagustlr677** [comment]
사진 불러오고, 숨길 메시지를 입력-> 숨길 메시지의 길이를 측정하여 필요한 만큼의 비트를 이미지에서 추출해냄(메시지x7x8정도) -> 메시지가 터키어가 아니거나 아스키범위가 아니면 에러(한국어 추가하는 기능도 있음좋을듯) ->입력한 메시지를 이진수로 나열하고,이진수 7자리가 아니면 앞을 0으로 패딩함-> 추출해낸 이미지비트에서 7자리와 입력한 메시지 1자리 (이진수) 를 합쳐 새로운8비트를 만듬. 이 작업을 추출해낸 이미지비트크기가 될때까지 반복 -> 이미지비트를 이것으로변경

예시) ab를 입력하였다. 거기서 (ab면 9798->11000011100010 스트링형식) 이것이 삽입비트이다. 삽입할 비트가 14개이니 각 비트를 하나씩 삽입하기 위해서 총 112비트가 필요하다.(8비트당 하나씩 삽입할것임) 따라서 이미지에서 112비트만큼을 추출해낸다. 그 수는 1111111111111111111111101111111011111111111111101111111011111111111111111111111011111110111111111111111011111110 가 된다고 하고 이걸 이미지비트라고 한다. 앞에자리부터 7개씩 따내고, 한자리는 삽입비트를 앞에서부터 추출해내서 총 8비트의 수가 만들어진다.("1111111"과 "1" 따라서 "11111111"이 됨) 그것을 112비트가 될때까지 반복한다. 즉 LSB를 버리고 삽입비트를 넣는것이다.

**Comment by SeungyeonKang** [comment]
오.. 이해가 쉽네요! 오픈소스 수업시간에 배운 것처럼 LSB를 이용한 것이군요!

**Comment by ur0n2** [comment]
`  if (((_form.ImageWidth * (_form.ImageHeight - 1) * 3) / 7) < _form.ImportTextBoxText.Length)`
이 코드 어떻게 보셨나요?

**Comment by SeungyeonKang** [comment]
다같이 코드를 분석한 결과 텍스트의 길이는 가장 왼쪽 아랫줄 픽셀에
텍스트는 왼쪽 맨 첫 줄의 픽셀부터 임포트하는 것으로 의견을 수렴했습니다. @rlagustlr677 @ur0n2
